applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: will-ci-cd
      namespaces:
        - name: will-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: will-dev
          bindings: *binds
          operatorgroup: true
        - name: will-test
          bindings: *binds
          operatorgroup: true
        - name: will-stage
          bindings: *binds
          operatorgroup: true

  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.6"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: GITLAB_DEFAULT_BRANCH
            value: 'main'
          - name: GITLAB_HOST
            value: 'gitlab-ce.apps.tl500-cwl.ls-ap.ole.redhat.com'
          - name: GITLAB_GROUP_NAME
            value: 'will'
          - name: GIT_SSL_NO_VERIFY
            value: "true"
          - name: JAVA_ARGS
            value: '-Dorg.jenkinsci.plugins.gitclient.GitClient.untrustedSSL=true'
          - name: Hello
            value: 'World'
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123

  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.10"
    values:
      includeRHRepositories: false
      service:
        name: nexus



  # Sealed Secrets
  - name: sealed-secrets
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: helper-sealed-secrets
    source_ref: "1.0.3"
    values:
      secrets:
        # Additional secrets will be added to this list along the exercises.
        - name: git-auth
          type: kubernetes.io/basic-auth
          annotations:
            tekton.dev/git-0: https://gitlab-ce.apps.tl500-cwl.ls-ap.ole.redhat.com
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgCc4K6ShytzajI5k+gYL7Z7prxJH7sSULW+sqmPxBJzfSMAf4X3m345CqUz7E5QRWqldOYAZiBHai5AGQAxxXCD7EQasO4s886CXBE1QZchh+dn9zkq3nndpcm1Np3KdjfeCtS26C3d65ylD4FZ3uxhPKzdV3Jy+hE7qf0S/bst1HatI9awZLyrhJ7OBZCO4qmL/GRa3qSejyPp3+XknjEvkrp4E2j4jkL1WQR1JwJbIAqihjsURJQ5qZCHVDkODdLbp1qBbgjxm8WZV2XAn/ZUMixlyqzZmyElaWac0Fe7RZW7Q9jDp82y8KQEU2ckDjmvGekUkE3U4g4My4ZsLVmLGBf7HIt1UhNi6dCSZ0Q3d5AKxSDd10NveQT8DfOY83WtR9b3YyhpkK/JPZPGF0zBWTvSH1Dp1K1/3vlbnOOq6yPU4VuCOhgU8fcGc0MjR/PUpNX57oiNoOe8OAUEWtoc2rgoMguIdxR37oculj6H4jPPdOi2Df+dSBVWIHJfrB3gvE1l28Ivw76CXokLCDaUrmVC+lDHeAxiqxsi/+tHzixwPevaXJqY9SpQVSEJFKH1N6wY+hLDLqkROm3XsfixSk3tUieoWqkINw+3fGwcL59MiKdjH4qhs3aBYY24KPpJj4wNoeDmzAUeSb5TjIUncf9UN0YanpqIoYTBRnvK278XeTrihCI5hBR0/j89+J+YnJxrKAI=
            password: AgB/PVmtfYYTfZoUDl702T86+dOyyazpvr/6OdYypBjt3c9EAJeNxsUEivpRk10BVtnOWn/RMKDquf+rOroyC2IfzZ8BuOwJdrXldYQhjKlp0mOn6g7TfZEU9e99FihRVGluJb7uYaPRsfrNfjsB19GZgUHwwUlhAOBtBiFifjyvxDoVvRHgQb/FzUlEt8C3QxDytzJ92jNhvrbb5FE1nvUrxEm+akEpDZq6KGYzGwj3ZvUNwAKbb5j72PPhChRdjtz6Dl2EPNr1Ij62AE5WLNxBXKiqfklE1kNmdxrkbARXK7EnrJdu0U951vX3TVqqrlXth/vMaHc9pCUCeV8xF7QweXfjs6Gsjr/z/7S1xeKhcjtf/i1x8FGoY62asQSeD8Vv26oN0BvaebQvrWlG90uhQrkJei7nW7EdGuQmlQntmtpwUgfc5Oy36mObYxP0J8yxzsLophRDw+hZXyfpSyjhi+QAB4XRLxbcsYzVUyQaNpdMfWeWQBCo7nb2nCZ+w5FyjH+ZbZsR9x2Egc5TaBgn1Z3b/nMJ4A9Xr/+KtTzoH7CL0GEmeoI3JzGcHfkvaduSXWP84sVIyrOEK6eBvpyMYULaPCXvF6WnzcM4kqLbT7q4Zgh4cD8hT2KpUrgyz3FcgAMj6vO6NAsttvZ9eX/RZm0VQJEyFr7GL1z0ZaapomH/w0XEnExr71XP+kCqZQpSJm0BiiJLFKx5FpxZ6/UMcuNj0w==
        - name: sonarqube-auth
          type: Opaque
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgBEQvKUKuTd55doWD5itM0g5/tZu2ek8I5xdAzPczCofco4BWBNgWMEqwDe/MpxGoh+Hby81Od99zEkFjCTqSwqgmj4G1oPwg1G4Fj0vqMlTOsfmMJ/MNKgFEks3au5VByylVBJWS1tNaWf2Nssx9wXHkyZNlFZf8Ccxtf5PzoIkTFXPXtndLKD7mD7JUqnkUCaWud9jSL9tzpaiZfFnmrvMca8wxonweT5IJW2A2Wn61kWOeiiaGe1g5os1fze35i1lLwti+X/3fFA7w5I0EOzObpNrZKJjKcTDErqyn27z+Sgys+TGQUZUkcYUXd+CPPFtgvkNEJcRII5DREfPrRxp7ob9BaIovUJGWA7wZjBVUbB0XgwpJZSHGQM/2nGMhGp+j5f6lgH7RmPc0IY+g7wa8Vw1li6HxoLF71WMEiAPH8kAlcepnxg06Nqbwd9WPE2Z7VsY/d/15oBdFwjOI4JZvhMzZMpsFDbZbb6ZDokK6J5aCtO30C/fLurF+FNBgyvbpw6phD0nrmbtUFzDCOyaqpwfJLt5a2M6vjrMCvt+vnfk4YlDZMp5UgKGP3HGcVJqve8Q007/2gUH+9Fa4J0zmOJFl+idwuD4Jrlx8o5GN9SgYCpjzX4CiS6VJ6KlEZMEaFxpEZKvacxC/JopOfuHw7VFmB3Hpe+enitCPiqtkygSyz4gu9Q+6GmUdKDoMyCES42YA==
            password: AgArfJ3FpGD+o19/PFptS3e/1es42X3+QIZR77BmgbOvmtXoN89AhZbYlPQmxaaqM2wfAXVdnWyuhingoibm7WH1d7fh2HzS1N/NYNpmHfLqfbRHbz6/G9XUgU/+UiULE7EVW6e6RvAlzGIE/cJOwqp/kNYwCKqY2YkJTN0nzt2+psdIRVLfZ+eis69Hqdz0+cAIfQfcqIBfRFWfwG0tMS95Q/lyAelweAIgoEtyvuStmjMMkNky7RXVxxTEs9PqX7X3qt4SWBzrcYBVO4hwmYZ7rP8QfZaOrxSPrdvFuLrnd5mNhbWxsE6pugJo8cNq7Jj4+B/YUaSyzuGkCfsGOKfIDlOi7MLUjijFsdW6+oRXtMOyu0O+lAxzl10UbK5Wk2Vu7qs3sbPMgeMlJU7Q0xqbTJDz61J4vVhdhNB1asjkxCoWsDEqEnkwRoxJEoMqu0GZTm7UxJPFMiDDS3tuCNvgRR2rCY2/FXT2DdzpOyUElX59kDcWbiJ/lnAVf7dqUU84MhDCbigVmoIfcCMk7ZCHVd1axr6o31KVfsjmG6KB5GhKcVkcO1bLSaMZ7Ckci4c0l3mcu/U6AoaYH0fuufZfVL1LfeM2awJ9pG8oqj2luVo++QB5Hm9YffhHB7ZnBOKGfqxXu886fYoomZ0uhVzf0KKLDgQLrqh5FSt/2youosES71rsYmviuw2p5WznUV/31H92dFOiDw==
            currentAdminPassword: AgBts3ayivmJg7YRj42zn1oT+L8afbCEshjbpxzsVor6IUfEzurL8eZdCQmob2Nwlk4ZhxrmRgR7z9ZBjHDBfMjoB0b9W6A6cPRq/1sK+zNK4Llm6761tDY539GpV2zju5at6O+0PKtDdVqiqB5wm/a2stMkAZwA/UIWqzIpSTxzqbGehazMxarQwnjpA1Qiwzir7rVzBy+kqU2T264j6NuGWdvlSXj5J2yeJXpsB/8ZPz4g+tKq5sGKaHqoxcy8Qj60DR0+rKET8eXLQeX4JxOXldoufp/QTLeBfLhUFahh5RpA09ptj+z7uIPdQv44+OUsx9DOlt2LbD/rfrn/gcQzMvw4HhLeXClzrEWmGbggXLeWb1iULuP4vhMX9nSwDi20agUZ1jYsvfd3W4l0VoiNz9A4go+VZKN8IyKj8o5FBCuSudv7BbluD9G1qfK5rqSZxLfYDbcGpyMtWDl/EZHciVfMA3KuwB44irp37hpk6c9zRFiDdbR4wJw4Xayzi0vALX4SeaR+ZdAEZxu9exnE/4TEoQw2rdYZg6meTjmhDy1k2vpmOdQjQsUWiuvBZP1x5qZ8PladzbZhjEwmamaSlOwBRdNtB8j6v1xrtCt7FqXrJgYUaDO9Q+1E8oWwLUKT226pwMxO5U50Ebv42odB30xxeJUhJEJOO3YU1Xa3Basd4tJZHFfuvynqPXbGVh+8ja0mlw==
        - name: allure-auth
          type: Opaque
          data:
            username: AgCbmEFvMiaqgS7vX1gCeO8ZpTB0AJA7WuNRHTsGU4lJTZybGYda24Wj63pyIjv+PZJ2/Pga+k5OhbzsebaoPTp+ocBA94T6V/n0h0Rjj5oYqWGG6R5WkMbKWbRJ4qjuQys0PjEHa60umwKUwll/n5Z9j/kvvbkRX/A4WU4S3OOhTNI/5TM9YswcQcMFd1JF9aH4eGjj7lyQeCWpQ9U7NJ+Ew1Zge4WhLWbWLFfeTdMI6ZffH03XOW4HGSaXmkfet6+v3aOR13iQn/4rxHJJo5pXUPjsrAR1b4UM9Ta31ZqDaYimdUFpz1CywXu3kcRLXLUvtQ/MpF0NDpe9ZeS9fTkJyM7RnCTthWSvSPtMjOMkcj5Yb70SMLE1onAecmciCJT1o/cHnpOLI3gm1YDnB46iam4o2OfkdP8PsGX3kZR6TxoHoB26le/nzQGunaMVCu9w+2BdjAYmn79PQmvzDXraRHxO7gxFNSDZmOpsNOcZoeaHj44iXgGJCjdOXI5ES6q6g4cp6/iTiar3MZDVeZFprNkbpH7imgBqcje5KnijJ1e6zgWwSeT87aNnh/Uro25VZdwd5yR7noLraIHy+CwAF0KWvC+nR6jq5n69Hrf0IJU1+390yW68edsqXOnlYI4R98FxF6b6RJegQuskXowqVaXhUMhpI55uYPYhnbg7a7D9+RirZbyRjY88arowGwm4xo90zg==
            password: AgBGOjqdrEYsatov6YS6eieQ1FAKbZI8PYrKi6ciKqtEF1ig9PnE249zGQEEb+j9rpw55ziBe2R/4+oTUHM4sdkB+5rZ5sYweNtMN9HZJTyp2LxWhNdHUeWgMkrUvCcy8GEj5yCMxfDH42oIauW/j7QKE39v6F9wgoTBFHUMYuTVV+/gJoR0UKN+WbaAgxrVm5wR41rZLiHzT6scH6QpOjWDMASxu9mMqkpAfxOZtSZ18/YEJx6JHrKfU3X2+EOWW2TWpClAZmEYpTiH/c1Ygvxt5TeI//nmz0oh4Qb/tWymCrsYuqA3KcSvZdwTnV587q03hvDVNJIcHaDzKfCVmKqK7BuIh6Ot0Z2E+Q8lrofeFl5dpWlbHe9PRpxBWQ26PAPHQDEjUsur1UzB7irenQouokSPtSENOUcCP8iuJRkOp60+KEy4TT5osbgHsluAedTB40zFTr/2psD3skdKMYAX7AZw08Cc4tCjbDA+lVENhUNbCuadZ5J3deHlXhg/JVd+q6Vw6s9qX2vw2vDFd96zu7zzg2qNFWC+VhHw7byAsdz8tkRvdh4iGJtvs/6mk6c2kba3ARrdKFgS3AzkKeNIoCBPuuzC00w2ANFfGTuwaVDvL4zeE9xnw+jXEGmP7jZgcR3w3+sv8N+ii73u0gRsRO4ozh8WlIr/M2Kbr8A0Myes0lJjNobZjslbjj8s4C17m6YCSUUAdg==




  # Tekton Pipelines
  - name: tekton-pipeline
    enabled: true
    source: "https://gitlab-ce.apps.tl500-cwl.ls-ap.ole.redhat.com/will/tech-exercise.git"
    source_ref: main
    source_path: tekton
    values:
      team: will
      cluster_domain: apps.tl500-cwl.ls-ap.ole.redhat.com
      git_server: gitlab-ce.apps.tl500-cwl.ls-ap.ole.redhat.com



  # Sonarqube
  - name: sonarqube
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonarqube
    source_ref: "0.1.0"
    values:
      account:
        existingSecret: sonarqube-auth
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/9.2/checkstyle-sonar-plugin-9.2.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar


  # Grafana


  # Allure
  - name: allure
    enabled: true
    source: https://github.com/eformat/allure.git
    source_path: "chart"
    source_ref: "main"
    values:
      security:
        secret: allure-auth



  # Matomo
